# Especificación a usar por docker compose
version: "3.9"

services:
  # Configurando MySql
  mysql-db:
    container_name: mysql-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_usuarios
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: dmedinao11/usuarios
# Usando construcción local
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - spring
    environment:
      PORT: 8001
      DB_HOST: mysql-db:3306
      DB_NAME: micro_usuarios
#    env_file:
#      - ./msvc-usuarios/.env
    depends_on:
      - mysql-db
    restart: on-failure

# Definiendo volumes
volumes:
  mysql-data:
    # Se coloca el name para que utilice el volume local
    name: mysql-data
# Definiendo redes
networks:
  spring:
