# Especificación a usar por docker compose
version: "3.9"

services:
  # Configurando Postgres
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: micro_cursos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring
      -
  msvc-cursos:
    container_name: msvc-cursos
    image: dmedinao11/cursos
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - spring
    environment:
      PORT: 8002
      DB_HOST: postgres-db:5432
      DB_NAME: micro_cursos
      MSVC_USUARIOS_URL: ec2-3-83-254-19.compute-1.amazonaws.com:8001
    depends_on:
      - postgres-db

# Definiendo volumes
volumes:
  postgres-data:
    name: postgres-data
# Definiendo redes
networks:
  spring:
